### ISSUE TITLE
No such file or directory: '/home/$USER/infore/datacron/implementation/parameter_optimizer/scripts/tmp/ids.txt'

### ISSUE THREAD

**Issue by aizazulhaq** [GiannisFikioris/Genetic-Algorithm-for-Synopses-Generator#3] opened 2021-02-04 18:29 UTC
The issue stems from line 354 in local_lib.py. The directory is hardcoded and it always looks for the file in '/home/$USER/infore/datacron/implementation/parameter_optimizer/scripts/tmp/ids.txt'

However, when I clone this repo, the directory should come out as:
'/home/$USER/infore/Genetic-Algorithm-for-Synopses-Generator/implementation/parameter_optimizer/scripts/tmp/ids.txt'

**Comment by GiannisFikioris** [comment] 2021-02-05 22:58
You are right, thanks for that!
The issue is that the installation instructions have a small mistake. It is now fixed. The file you mention should be in the first path, as in the 'local_lib.py' file, i.e. you should rename the 'Genetic-Algorithm-for-Synopses-Generator' folder to 'datacron'.

**Closed as completed** 2021-02-05 23:38 UTC
